name = "compression_server"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gtempo = ">= 4.2.0 and < 5.0.0"
ansel = { path = "../ansel" }
snag = ">= 0.3.0 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gsiphash = ">= 1.0.0 and < 2.0.0"
sqlight = ">= 0.9.1 and < 1.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
filespy = ">= 0.5.0 and < 1.0.0"
gleam_otp = ">= 0.12.1 and < 1.0.0"
repeatedly = ">= 2.1.1 and < 3.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_httpc = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
glenvy = ">= 1.0.1 and < 2.0.0"
nextexif = ">= 0.1.2 and < 1.0.0"
gleam_erlang = ">= 0.27.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glychee = ">= 1.1.2 and < 2.0.0"
